### ISSUE TITLE
DonoThumbnail needs to navigate to 3 different places based on donostatus.

### ISSUE THREAD

**Issue by carsondavies** [wr4-dono/dono#25]

**Comment by jButters7** [comment]
Is the thid location the Ratings page?
Locations
1. Accepted button (appear if user is not giver) -> AcceptedPost.js
2. Edit Button (appear if user is giver) -> NewDono.js
3. Continue Chatting (appear if user on redux is giver/carrier) -> AcceptedPost.js
4. Ratings (RateUser) (if dono status is 3) -> RateUser.js

**Comment by jButters7** [comment]
We have gotten this completed. besides continue chatting it takes the user first to the singledono.js
